spring:
  datasource:
    url: jdbc:mysql://rm-2zez6a4q4b1srt5m1ro.mysql.rds.aliyuncs.com:3306/vela_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: hkttty0001
    password: Naya00001
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 20000
    minEvictableIdleTimeMillis: 20000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080
  address: 0.0.0.0

mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: false
logging:
  file:
    max-history: 48
    max-size: 1000
    path: src/mylog.log
  level:
    com:
      mp:
        generator:
          controller:
            SysUserController: info
  pattern:
    dateformat: yyyy-MM-dd

